/**
 * Typed shapes of the eight outbound webhook events.
 *
 * Generated by scripts/generate_event_types.py from docs/reference/webhook-events.json.
 * Do not edit: CI regenerates this file and fails on any difference.
 *
 * `type` is a literal, so the union narrows on a switch:
 *
 *     if (event.type === 'deposit.settled') {
 *       credit(event.data.amount_credited);
 *     }
 */

/**
 * A payment is visible. It is **not** credited yet — `amount_credited` may still be zero.
 */
export interface DepositDetectedData {
  deposit_id: string;
  external_user_id: string;
  asset: string;
  status: string;
  /** * Decimal string, the running total credited to the user for this deposit. */
  amount_credited: string;
  /** * BTCPay payment ids recorded by this update. */
  payments: string[];
}

export interface DepositEventData {
  deposit_id: string;
  external_user_id: string;
  asset: string;
  status: string;
  /** * Decimal string, the running total credited to the user for this deposit. */
  amount_credited: string;
}

/**
 * A withdrawal that stopped, or stopped to wait. The reason is always present.
 *
 * Every path that queues a withdrawal names the gate that fired, and every
 * path that fails one names why, so this field is required rather than
 * optional — a `withdrawal.failed` with no reason would be the one event an
 * operator cannot act on.
 */
export interface WithdrawalDecisionData {
  withdrawal_id: string;
  external_user_id: string;
  asset: string;
  status: string;
  amount_gross: string;
  /** * `null` until submission fixes the fee. */
  amount_net: string | null;
  /** * `null` until submission fixes the fee. */
  fee: string | null;
  destination_address: string;
  txid: string | null;
  /**
   * For `pending_approval`, which gate fired. For `failed`, why it will not proceed —
   * including a machine-generated definitive-failure proof where the backend can produce one.
   */
  reason: string;
}

export interface WithdrawalEventData {
  withdrawal_id: string;
  external_user_id: string;
  asset: string;
  status: string;
  amount_gross: string;
  /** * `null` until submission fixes the fee. */
  amount_net: string | null;
  /** * `null` until submission fixes the fee. */
  fee: string | null;
  destination_address: string;
  txid: string | null;
}

export interface DepositDetectedEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'deposit.detected';
  data: DepositDetectedData;
}

export interface DepositExpiredEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'deposit.expired';
  data: DepositEventData;
}

export interface DepositReviewRequiredEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'deposit.review_required';
  data: DepositEventData;
}

export interface DepositSettledEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'deposit.settled';
  data: DepositEventData;
}

export interface WithdrawalBroadcastEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'withdrawal.broadcast';
  data: WithdrawalEventData;
}

export interface WithdrawalCompletedEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'withdrawal.completed';
  data: WithdrawalEventData;
}

/**
 * **The money is not back yet.** A failed withdrawal still holds the balance.
 */
export interface WithdrawalFailedEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'withdrawal.failed';
  data: WithdrawalDecisionData;
}

export interface WithdrawalPendingApprovalEvent {
  /** * Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice. */
  id: string;
  created_at: string;
  type: 'withdrawal.pending_approval';
  data: WithdrawalDecisionData;
}

/** Every event the service sends, discriminated on `type`. */
export type PlatformEvent =
  | DepositDetectedEvent
  | DepositExpiredEvent
  | DepositReviewRequiredEvent
  | DepositSettledEvent
  | WithdrawalBroadcastEvent
  | WithdrawalCompletedEvent
  | WithdrawalFailedEvent
  | WithdrawalPendingApprovalEvent;

/** The `type` values, as a type. */
export type EventType = PlatformEvent['type'];

/** The same closed set at runtime, in the order the schema lists it. */
export const EVENT_TYPES = [
  'deposit.detected',
  'deposit.expired',
  'deposit.review_required',
  'deposit.settled',
  'withdrawal.broadcast',
  'withdrawal.completed',
  'withdrawal.failed',
  'withdrawal.pending_approval',
] as const satisfies readonly EventType[];
