/**
 * TypeScript client for crypto-processing-api.
 *
 * ```ts
 * import { CryptoProcessingClient, parseEvent } from '@oliverd25/crypto-processing-client';
 *
 * const client = new CryptoProcessingClient({
 *   baseUrl: 'https://pay.example.com',
 *   apiKey: 'cpk_live_...',
 * });
 * const deposit = await client.createDeposit({ external_user_id: 'user-42', asset: 'BTC' });
 * ```
 *
 * The version tracks the server it supports: `client 0.N.x` works against
 * `server 0.N.y`. See `docs/reference/versioning.md` in the repository.
 *
 * Two layers live here. `src/generated` is produced from the server's
 * committed OpenAPI document and is regenerated by CI, which fails on any
 * difference — so it cannot describe a server that does not exist. Everything
 * else is the handwritten part: idempotency keys, retries, typed errors and
 * webhook verification, none of which codegen can write.
 */

export {
  CryptoProcessingClient,
  DEFAULT_RETRY,
  retryAfterSeconds,
  type CryptoProcessingClientOptions,
  type RetryPolicy,
} from './client.js';

export {
  ApiError,
  AuthenticationError,
  BadRequestError,
  ConflictError,
  CryptoProcessingError,
  NotFoundError,
  PermissionDeniedError,
  ServerError,
  ServiceUnavailableError,
  TransportError,
  UnknownEventTypeError,
  UpstreamRefusedError,
  ValidationError,
  WebhookVerificationError,
  type ApiErrorInit,
} from './errors.js';

export {
  EVENT_TYPES,
  type DepositDetectedData,
  type DepositDetectedEvent,
  type DepositEventData,
  type DepositExpiredEvent,
  type DepositReviewRequiredEvent,
  type DepositSettledEvent,
  type EventType,
  type PlatformEvent,
  type WithdrawalBroadcastEvent,
  type WithdrawalCompletedEvent,
  type WithdrawalDecisionData,
  type WithdrawalEventData,
  type WithdrawalFailedEvent,
  type WithdrawalPendingApprovalEvent,
} from './event-types.js';

export {
  REPLAY_WINDOW_SECONDS,
  SIGNATURE_HEADER,
  parseEvent,
  parseEventUnverified,
  verifyWebhook,
  type BodySource,
  type HeaderSource,
  type VerifyOptions,
} from './webhooks.js';

export type {
  AddressHistoryResponse,
  AddressReservationResponse,
  AdminDepositQueueResponse,
  AdminWithdrawalListResponse,
  AdminWithdrawalResponse,
  ApproveWithdrawalRequest,
  AssetResponse,
  AssetsResponse,
  BalanceResponse,
  BalancesResponse,
  ComponentResponse,
  CreateDepositRequest,
  CreateWithdrawalRequest,
  CustodyLineResponse,
  DepositListResponse,
  DepositPaymentResponse,
  DepositResponse,
  ErrorResponse,
  HealthResponse,
  MarkBroadcastRequest,
  OutboundEventResponse,
  OutboundEventsResponse,
  ReadyResponse,
  ReconciliationResponse,
  RedeliverEventResponse,
  RejectWithdrawalRequest,
  ReleaseWithdrawalRequest,
  ResolveDepositRequest,
  TransactionResponse,
  TransactionsResponse,
  WalletAlertResponse,
  WalletAlertsResponse,
  WithdrawalCreatedResponse,
  WithdrawalListResponse,
  WithdrawalResponse,
} from './generated/types.gen.js';
