"""Migrations must be reversible, and reversible back to the same schema.

The failure this catches: a `downgrade` that forgets one object. This schema is
mostly made of the things people forget — an enum value, an append-only
trigger, a partial unique index, a CHECK. None of them break anything until the
day someone actually downgrades, which is the worst possible day to find out.

The comparison is a normalized fingerprint from `pg_catalog`, not a `pg_dump`.
See `crypto_processing_api.testing.schema` for why.
"""

from __future__ import annotations

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import Engine, text

from crypto_processing_api.testing.schema import public_tables, schema_fingerprint

pytestmark = pytest.mark.integration


@pytest.fixture
def alembic_config(alembic_ini: Config) -> Config:
    return alembic_ini


def test_downgrade_then_upgrade_reproduces_the_schema_exactly(
    engine: Engine, alembic_config: Config
) -> None:
    with engine.connect() as connection:
        before = schema_fingerprint(connection)

    command.downgrade(alembic_config, "base")

    with engine.connect() as connection:
        remaining = [name for name in public_tables(connection) if name != "alembic_version"]
    assert remaining == [], (
        f"downgrade left {remaining} behind; a downgrade that does not undo itself "
        "makes the next one unpredictable"
    )

    command.upgrade(alembic_config, "head")

    with engine.connect() as connection:
        after = schema_fingerprint(connection)

    if before != after:
        before_lines = set(before.splitlines())
        after_lines = set(after.splitlines())
        lost = sorted(before_lines - after_lines)
        gained = sorted(after_lines - before_lines)
        pytest.fail(
            "the schema after downgrade+upgrade differs from the schema before.\n"
            f"missing after round trip: {lost}\n"
            f"unexpectedly present:     {gained}"
        )


def test_the_fingerprint_notices_a_dropped_object(engine: Engine) -> None:
    """A test that cannot fail is not evidence. This proves it can."""
    with engine.connect() as connection:
        original = schema_fingerprint(connection)

    with engine.begin() as connection:
        connection.execute(text("DROP INDEX ux_withdrawals_txid"))
    try:
        with engine.connect() as connection:
            damaged = schema_fingerprint(connection)
        assert damaged != original
        assert "ux_withdrawals_txid" in original
        assert "ux_withdrawals_txid" not in damaged
    finally:
        with engine.begin() as connection:
            connection.execute(
                text(
                    "CREATE UNIQUE INDEX ux_withdrawals_txid ON withdrawals (txid) "
                    "WHERE txid IS NOT NULL"
                )
            )


def test_there_is_exactly_one_migration_head(alembic_config: Config) -> None:
    """Two heads mean a merge created a branch point and migrations stop being ordered."""
    heads = ScriptDirectory.from_config(alembic_config).get_heads()
    assert len(heads) == 1, f"expected one head, found {heads}"


def test_the_models_and_the_migrations_agree(engine: Engine, alembic_config: Config) -> None:
    """`alembic check` — catches a model edited without a migration.

    The whole point is that nothing warns you otherwise: the ORM happily
    queries a column the database does not have until the first request that
    needs it.
    """
    from alembic.util.exc import AutogenerateDiffsDetected

    try:
        command.check(alembic_config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "ledger/models.py and the migrations have diverged. Either the model "
            f"changed without a migration, or the migration is incomplete:\n{exc}"
        )
