"""This client's verifier must agree with the server's, case for case.

`sdks/signature-vectors.json` is generated by the server's own signer and is
asserted by the server suite, this suite and the TypeScript suite. It is the
only thing that makes "the SDK verifies webhooks correctly" a checkable claim
rather than a hope.
"""

from __future__ import annotations

import base64
import json
from pathlib import Path
from typing import Any

import pytest

from crypto_processing_client import (
    EVENT_TYPES,
    REPLAY_WINDOW_SECONDS,
    SIGNATURE_HEADER,
    parse_event_unverified,
    verify_webhook,
)

VECTORS_PATH = Path(__file__).resolve().parents[2] / "signature-vectors.json"


def _load() -> dict[str, Any]:
    assert VECTORS_PATH.exists(), (
        f"{VECTORS_PATH} is missing. It is generated by "
        "`python scripts/export_signature_vectors.py` in the server repository."
    )
    document: dict[str, Any] = json.loads(VECTORS_PATH.read_text(encoding="utf-8"))
    return document


VECTORS = _load()


def body_of(name: str) -> bytes:
    return base64.b64decode(VECTORS["bodies"][name]["base64"])


def test_the_scheme_constants_match_the_server() -> None:
    assert VECTORS["scheme"]["header"] == SIGNATURE_HEADER
    assert VECTORS["scheme"]["replay_window_seconds"] == REPLAY_WINDOW_SECONDS


@pytest.mark.parametrize("case", VECTORS["sign"], ids=lambda case: str(case["name"]))
def test_every_signed_vector_verifies(case: dict[str, Any]) -> None:
    """A signature the server produced must be one this client accepts."""
    assert verify_webhook(
        body_of(case["body"]),
        case["signature"],
        case["secret"],
        now=case["timestamp"],
    ), case["name"]


@pytest.mark.parametrize("case", VECTORS["verify"], ids=lambda case: str(case["name"]))
def test_every_verify_vector_gets_the_same_answer(case: dict[str, Any]) -> None:
    accepted = verify_webhook(
        body_of(case["body"]), case["header"], case["secret"], now=case["now"]
    )
    assert accepted is case["valid"], f"{case['name']}: {case['why']}"


def test_the_matrix_contains_refusals() -> None:
    """Guards the guard: passing cases alone would be satisfied by `return True`."""
    assert {case["valid"] for case in VECTORS["verify"]} == {True, False}


@pytest.mark.parametrize("event_type", EVENT_TYPES)
def test_every_real_event_body_parses(event_type: str) -> None:
    """The vector bodies are the delivery worker's own bytes, not a hand-typed sample."""
    event = parse_event_unverified(body_of(f"event.{event_type}"))
    assert event["type"] == event_type
    assert event["id"].startswith("evt_")
    assert event["data"]
