#!/usr/bin/env python
"""Configure a BTCPay Server instance for this service. Safe to re-run.

    python scripts/bootstrap_btcpay.py

Against the regtest stack it creates, in order: the first admin user, a store,
a BTCPay-generated hot wallet, the settlement speed policy, a webhook pointing
at the api container, and a Greenfield API key holding only the scopes this
service needs. Ids and secrets land in .env.regtest.generated, which is
gitignored.

Every step checks for the object before creating it, so a second run reports
"exists" and changes nothing. The one exception is the webhook secret: BTCPay
never returns it after creation, so if the webhook exists and we have no
recorded secret, a fresh one is written to both sides.

A hot wallet is required, not a watch-only xpub: BTCPay's automated payout
processor has to sign. On regtest that is free; in production it is the reason
the float is the loss ceiling.
"""

from __future__ import annotations

import base64
import contextlib
import json
import os
import secrets
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import httpx

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / ".env.regtest.generated"

BTC_PAYMENT_METHOD_ID = "BTC-CHAIN"

# 1 confirmation. HighSpeed (0-conf) would credit deposits that a single-block
# reorg can still take away, and regtest is where that habit gets formed.
SPEED_POLICY = "MediumSpeed"

WEBHOOK_EVENTS = [
    "InvoiceReceivedPayment",
    "InvoiceProcessing",
    "InvoicePaymentSettled",
    "InvoiceSettled",
    "InvoiceExpired",
    "InvoiceInvalid",
    "PayoutCreated",
    "PayoutApproved",
    "PayoutUpdated",
]


# Minimal scopes, all pinned to the one store. Webhook management and
# payout-processor configuration are deliberately absent: those are bootstrap
# operations and run under the admin's Basic auth, not under the key the
# service carries at runtime.
def store_scopes(store_id: str) -> list[str]:
    return [
        f"btcpay.store.cancreateinvoice:{store_id}",
        f"btcpay.store.canviewinvoices:{store_id}",
        f"btcpay.store.canmanagepullpayments:{store_id}",
        f"btcpay.store.canviewstoresettings:{store_id}",
    ]


def log(message: str) -> None:
    print(f"[bootstrap] {message}", file=sys.stderr)


class BootstrapError(RuntimeError):
    pass


@dataclass
class Config:
    url: str = field(
        default_factory=lambda: os.environ.get("BTCPAY_BOOTSTRAP_URL", "http://127.0.0.1:14142")
    )
    internal_url: str = field(
        default_factory=lambda: os.environ.get("BTCPAY_INTERNAL_URL", "http://btcpayserver:49392")
    )
    store_name: str = field(
        default_factory=lambda: os.environ.get("BTCPAY_STORE_NAME", "cpapi-regtest")
    )
    webhook_url: str = field(
        default_factory=lambda: os.environ.get(
            "BTCPAY_WEBHOOK_URL", "http://api:8000/webhooks/btcpay"
        )
    )
    admin_email: str = field(
        default_factory=lambda: os.environ.get("BTCPAY_ADMIN_EMAIL", "admin@cpapi.local")
    )
    admin_password: str = field(default_factory=lambda: os.environ.get("BTCPAY_ADMIN_PASSWORD", ""))
    output_path: Path = field(
        default_factory=lambda: Path(os.environ.get("BTCPAY_BOOTSTRAP_OUTPUT", DEFAULT_OUTPUT))
    )
    wait_seconds: int = field(
        default_factory=lambda: int(os.environ.get("BTCPAY_BOOTSTRAP_WAIT", "300"))
    )


def read_env_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def write_env_file(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by scripts/bootstrap_btcpay.py — do not commit.",
        "# Re-running the script keeps these values unless the object is gone.",
        "",
    ]
    lines.extend(f"{key}={value}" for key, value in sorted(values.items()))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    # Windows hosts do not honour POSIX modes; the file is gitignored either way.
    with contextlib.suppress(OSError):
        path.chmod(0o600)


def generate_password() -> str:
    # ASP.NET Identity wants a digit, both cases and a symbol.
    return f"{secrets.token_urlsafe(24)}aA1!"


class BTCPayAdmin:
    """Greenfield calls under the admin's Basic auth."""

    def __init__(self, base_url: str, email: str, password: str) -> None:
        self.base_url = base_url.rstrip("/")
        token = base64.b64encode(f"{email}:{password}".encode()).decode()
        self.client = httpx.Client(
            base_url=self.base_url,
            headers={"Authorization": f"Basic {token}"},
            timeout=httpx.Timeout(connect=5.0, read=60.0, write=30.0, pool=30.0),
        )

    def close(self) -> None:
        self.client.close()

    def request(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        return self.client.request(method, path, **kwargs)

    def json(self, method: str, path: str, **kwargs: Any) -> Any:
        response = self.request(method, path, **kwargs)
        if response.status_code >= 400:
            raise BootstrapError(
                f"{method} {path} -> {response.status_code}: {response.text[:400]}"
            )
        return response.json() if response.content else None


def wait_for_btcpay(config: Config) -> None:
    deadline = time.monotonic() + config.wait_seconds
    last_error = ""
    while time.monotonic() < deadline:
        try:
            response = httpx.get(f"{config.url.rstrip('/')}/api/v1/health", timeout=5.0)
            if response.status_code == 200:
                log(f"BTCPay is up: {response.text.strip()}")
                return
            last_error = f"HTTP {response.status_code}"
        except httpx.HTTPError as exc:
            last_error = type(exc).__name__
        time.sleep(3)
    raise BootstrapError(
        f"BTCPay at {config.url} did not answer /api/v1/health within "
        f"{config.wait_seconds}s (last: {last_error})"
    )


def ensure_admin_user(config: Config) -> BTCPayAdmin:
    admin = BTCPayAdmin(config.url, config.admin_email, config.admin_password)
    response = admin.request("GET", "/api/v1/users/me")
    if response.status_code == 200:
        log(f"admin user exists: {config.admin_email}")
        return admin

    created = httpx.post(
        f"{config.url.rstrip('/')}/api/v1/users",
        json={
            "email": config.admin_email,
            "password": config.admin_password,
            "isAdministrator": True,
        },
        timeout=30.0,
    )
    if created.status_code >= 400:
        admin.close()
        raise BootstrapError(
            "could not create the first admin user "
            f"({created.status_code}: {created.text[:300]}). If this BTCPay already has an "
            "admin, set BTCPAY_ADMIN_EMAIL and BTCPAY_ADMIN_PASSWORD to it, or wipe the "
            "stack with `docker compose -f deploy/docker-compose.regtest.yml down -v`."
        )
    log(f"created admin user {config.admin_email}")
    return admin


def ensure_store(admin: BTCPayAdmin, name: str) -> dict[str, Any]:
    stores: list[dict[str, Any]] = admin.json("GET", "/api/v1/stores") or []
    for store in stores:
        if store.get("name") == name:
            log(f"store exists: {name} ({store['id']})")
            return store
    store = admin.json("POST", "/api/v1/stores", json={"name": name, "speedPolicy": SPEED_POLICY})
    log(f"created store {name} ({store['id']})")
    return store


def ensure_speed_policy(admin: BTCPayAdmin, store: dict[str, Any]) -> None:
    if store.get("speedPolicy") == SPEED_POLICY:
        log(f"speed policy already {SPEED_POLICY}")
        return
    body = {key: value for key, value in store.items() if key != "id"}
    body["speedPolicy"] = SPEED_POLICY
    response = admin.request("PUT", f"/api/v1/stores/{store['id']}", json=body)
    if response.status_code >= 400:
        raise BootstrapError(
            f"could not set speedPolicy={SPEED_POLICY} "
            f"({response.status_code}: {response.text[:300]})"
        )
    log(f"speed policy set to {SPEED_POLICY}")


def ensure_hot_wallet(admin: BTCPayAdmin, store_id: str) -> None:
    existing = admin.request(
        "GET", f"/api/v1/stores/{store_id}/payment-methods/{BTC_PAYMENT_METHOD_ID}/wallet"
    )
    if existing.status_code == 200:
        log(f"hot wallet exists for {BTC_PAYMENT_METHOD_ID}")
        return

    admin.json(
        "POST",
        f"/api/v1/stores/{store_id}/payment-methods/{BTC_PAYMENT_METHOD_ID}/wallet/generate",
        json={
            "label": "cpapi hot wallet",
            "wordList": "English",
            "wordCount": 12,
            "scriptPubKeyType": "Segwit",
            # The automated payout processor has to sign, so BTCPay keeps the
            # seed. The mnemonic in the response is deliberately not written
            # anywhere by this script.
            "savePrivateKeys": True,
        },
    )
    log(f"generated hot wallet for {BTC_PAYMENT_METHOD_ID}")


def ensure_webhook(
    admin: BTCPayAdmin, store_id: str, url: str, known_secret: str
) -> tuple[str, str]:
    webhooks: list[dict[str, Any]] = admin.json("GET", f"/api/v1/stores/{store_id}/webhooks") or []
    body: dict[str, Any] = {
        "url": url,
        "enabled": True,
        # BTCPay's redelivery budget is small; our own worker owns retries. It
        # still costs nothing and covers a brief restart.
        "automaticRedelivery": True,
        "authorizedEvents": {"everything": False, "specificEvents": WEBHOOK_EVENTS},
    }

    for webhook in webhooks:
        if webhook.get("url") != url:
            continue
        if known_secret:
            log(f"webhook exists: {webhook['id']}")
            return str(webhook["id"]), known_secret
        secret = secrets.token_urlsafe(32)
        admin.json("PUT", f"/api/v1/webhooks/{webhook['id']}", json={**body, "secret": secret})
        log(f"webhook {webhook['id']} exists but its secret was unknown; rotated it")
        return str(webhook["id"]), secret

    secret = secrets.token_urlsafe(32)
    created = admin.json(
        "POST", f"/api/v1/stores/{store_id}/webhooks", json={**body, "secret": secret}
    )
    log(f"created webhook {created['id']} -> {url}")
    return str(created["id"]), str(created.get("secret") or secret)


def ensure_api_key(admin: BTCPayAdmin, config: Config, store_id: str, known_key: str) -> str:
    if known_key:
        response = httpx.get(
            f"{config.url.rstrip('/')}/api/v1/api-keys/current",
            headers={"Authorization": f"token {known_key}"},
            timeout=15.0,
        )
        if response.status_code == 200:
            log("greenfield API key still valid")
            return known_key
        log("recorded greenfield API key no longer works; issuing a new one")

    created = admin.json(
        "POST",
        "/api/v1/api-keys",
        json={"label": "cpapi service key", "permissions": store_scopes(store_id)},
    )
    log(f"issued greenfield API key with {len(store_scopes(store_id))} store-scoped permissions")
    return str(created["apiKey"])


def configure_payout_processor(store_id: str) -> None:
    """M3 STUB — intentionally does nothing yet.

    BTC withdrawals are M3. When they land, this configures
    OnChainAutomatedPayoutSenderFactory for BTC-CHAIN with
    intervalSeconds=5 on regtest (600 in production), feeTargetBlock=3 and
    processNewPayoutsInstantly=true, via
    PUT /api/v1/stores/{storeId}/payout-processors/
        OnChainAutomatedPayoutSenderFactory/BTC-CHAIN

    It is not configured now on purpose: a processor that broadcasts payouts
    should not exist before the code that decides which payouts are legal.
    """
    log(f"payout processor for store {store_id}: skipped, arrives with M3 withdrawals")


def main() -> int:
    config = Config()
    existing = read_env_file(config.output_path)

    if not config.admin_password:
        config.admin_password = existing.get("BTCPAY_ADMIN_PASSWORD") or generate_password()
    if "BTCPAY_ADMIN_EMAIL" in existing and not os.environ.get("BTCPAY_ADMIN_EMAIL"):
        config.admin_email = existing["BTCPAY_ADMIN_EMAIL"]

    wait_for_btcpay(config)
    admin = ensure_admin_user(config)
    try:
        store = ensure_store(admin, config.store_name)
        ensure_speed_policy(admin, store)
        store_id = str(store["id"])
        ensure_hot_wallet(admin, store_id)
        webhook_id, webhook_secret = ensure_webhook(
            admin, store_id, config.webhook_url, existing.get("BTCPAY_WEBHOOK_SECRET", "")
        )
        api_key = ensure_api_key(admin, config, store_id, existing.get("BTCPAY_API_KEY", ""))
        configure_payout_processor(store_id)
    finally:
        admin.close()

    values = {
        "BTCPAY_URL": config.internal_url,
        "BTCPAY_PUBLIC_URL": config.url,
        "BTCPAY_STORE_ID": store_id,
        "BTCPAY_API_KEY": api_key,
        "BTCPAY_WEBHOOK_ID": webhook_id,
        "BTCPAY_WEBHOOK_SECRET": webhook_secret,
        "BTCPAY_ADMIN_EMAIL": config.admin_email,
        "BTCPAY_ADMIN_PASSWORD": config.admin_password,
        "SEED_BTC_PAYMENT_METHOD": BTC_PAYMENT_METHOD_ID,
    }
    write_env_file(config.output_path, values)
    log(f"wrote {config.output_path}")
    log("store_id and webhook are ready; deposits are M2")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BootstrapError as error:
        print(json.dumps({"error": str(error)}), file=sys.stderr)
        raise SystemExit(1) from error
