"""Write the configuration reference to `docs/reference/configuration.md`.

Every environment variable the service reads is a field of `Settings`
(`src/crypto_processing_api/config.py`). That model is the only thing that can
be authoritative about the list, because it is what actually reads the
environment — and `.env.example`, being hand-maintained prose, had already
drifted ten variables behind it (issue #5).

So the page is generated from the model: the field list, the types, the
defaults and the `ge`/`gt`/`le` constraints come from pydantic, and the prose
comes from the `#:` comment above each field (or `Field(description=...)`,
which wins if both exist). Nothing on the page is written twice, which is the
whole point: a setting added to `Settings` appears here on the next run, and a
setting removed disappears.

The `#:` comments are read from the source with `ast` rather than from the
model, because pydantic does not keep them. `# === Name ===` lines inside the
class body become the section headings, in declaration order.

Drift-gated by CI exactly like the API contracts, and deterministic for the
same reason.

    python scripts/export_config_reference.py           # write
    python scripts/export_config_reference.py --check   # exit 1 if the tree is stale
"""

from __future__ import annotations

import argparse
import ast
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

#: Same placeholder as `export_openapi.py`: building `Settings` needs a URL that
#: passes validation, and nothing here ever connects.
PLACEHOLDER_DATABASE_URL = "postgresql+psycopg://spec:spec@localhost:5432/spec"
os.environ.setdefault("DATABASE_URL", PLACEHOLDER_DATABASE_URL)

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_SOURCE = REPO_ROOT / "src" / "crypto_processing_api" / "config.py"
OUTPUT_PATH = REPO_ROOT / "docs" / "reference" / "configuration.md"

#: A value under one of these names is never printed, in a log or here. The
#: page shows the variable and its meaning; the default is always "unset".
SECRET_SUBSTRINGS = ("secret", "api_key", "token")

#: Cross-field rules live in the `@model_validator`, which no amount of
#: introspection can turn into a sentence. They are listed by hand and kept
#: short — the authoritative version is the error the service refuses to start
#: with, and each line here names the variables so it is greppable.
STARTUP_RULES = [
    "`DEBUG=true` is allowed only with `ENVIRONMENT=development`. Debug mode "
    "leaks internals into responses and logs.",
    "`DATABASE_URL` must be a psycopg 3 PostgreSQL URL — `postgresql://` or "
    "`postgresql+psycopg://`.",
    "`SEED_BTC_WITHDRAWAL_AUTO_LIMIT`, `SEED_LN_WITHDRAWAL_AUTO_LIMIT` and "
    "`SEED_USDT_WITHDRAWAL_AUTO_LIMIT` may not exceed their matching "
    "`*_DAILY_CAP`. Otherwise one withdrawal could clear the 24-hour cap on its "
    "own.",
    "`BITCOIN_NETWORK` must be `mainnet` when `ENVIRONMENT=production`. "
    "Anything else validates withdrawal addresses against the wrong chain.",
    "`TRONGRID_API_KEY` is required in production once `TRON_HOT_WALLET_ADDRESS` "
    "is set. Keyless TronGrid access is throttled unpredictably, and what gets "
    "throttled is the check that a withdrawal really happened.",
    "`USDT_AUTO_WITHDRAW=true` is refused outright. The BTCPay USDt plugin has "
    "no payout handler, so an auto-approved USDT withdrawal would stall with "
    "the user's balance held.",
    "`PLATFORM_WEBHOOK_SECRET` is required once `PLATFORM_WEBHOOK_URL` is set. "
    "An unsigned webhook is one anybody can forge.",
    "`DEPOSIT_MONITORING_MINUTES` may not be below "
    "`DEPOSIT_INVOICE_EXPIRY_MIN_BTC`. BTCPay would stop attributing payments "
    "before the invoice had even expired.",
]

HEADER = """<!--
Generated by scripts/export_config_reference.py from the Settings model in
src/crypto_processing_api/config.py. Do not edit this file: run

    python scripts/export_config_reference.py

and commit the result. CI fails if the two disagree.
-->

# Configuration reference

Every variable this service reads, generated from the `Settings` model that
reads them. The environment is the only configuration source; a `.env` file
next to the process is read too, and a real environment variable wins over it.

[`.env.example`](https://github.com/OliverD25/crypto-processing-api/blob/main/.env.example)
is the annotated copy to start from — same variables, more operator prose. This
page is the one that cannot go out of date.

A **required** variable has no default and the process will not start without
it. Values marked **secret** are never logged and never printed by any
endpoint. Amounts are always integers in the asset's smallest unit — satoshis
for `BTC` and `BTC_LN`, micro-USDT for `USDT_TRC20`.
"""

RULES_HEADING = """
## Rules checked at startup

These are cross-field, so they are not visible in the table above. Each one is
a refusal to start, not a warning.
"""


@dataclass
class Entry:
    """One row of the table, or one section heading."""

    name: str
    section: str
    annotation: str
    description: str = ""
    default: str = ""
    required: bool = False
    constraint: str = ""
    secret: bool = field(default=False)


def _comment_block(lines: list[str], before: int) -> str:
    """The run of `#:` comment lines directly above source line `before`."""
    collected: list[str] = []
    index = before - 2  # `before` is 1-based; step to the line above it.
    while index >= 0:
        stripped = lines[index].strip()
        if not stripped.startswith("#:"):
            break
        collected.append(stripped[2:].strip())
        index -= 1
    return " ".join(reversed(collected))


def _field_description(node: ast.AnnAssign) -> str | None:
    """`Field(description=...)`, when the field declares one."""
    call = node.value
    if not isinstance(call, ast.Call):
        return None
    for keyword in call.keywords:
        if keyword.arg == "description" and isinstance(keyword.value, ast.Constant):
            value = keyword.value.value
            return value if isinstance(value, str) else None
    return None


def _source_metadata() -> tuple[dict[str, str], dict[str, str]]:
    """Per-field prose and section, read from `config.py` in declaration order."""
    source = CONFIG_SOURCE.read_text(encoding="utf-8")
    lines = source.splitlines()
    tree = ast.parse(source)

    settings = next(
        node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == "Settings"
    )

    # Section markers are comments, so they are not in the AST. Map every source
    # line to the most recent `# === Name ===` above it.
    section_at: list[str] = []
    current = ""
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("# === ") and stripped.endswith(" ==="):
            current = stripped[len("# === ") : -len(" ===")]
        section_at.append(current)

    descriptions: dict[str, str] = {}
    sections: dict[str, str] = {}
    for node in settings.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        name = node.target.id
        if name.startswith("_"):
            continue
        # The `#:` block sits above the whole statement, decorators included.
        first_line = min(node.lineno, getattr(node.annotation, "lineno", node.lineno))
        descriptions[name] = _field_description(node) or _comment_block(lines, first_line)
        sections[name] = section_at[node.lineno - 1]
    return descriptions, sections


def _render_default(value: Any) -> str:
    if value is None:
        return "*(unset)*"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    return f"`{value}`"


def _render_type(annotation: Any) -> str:
    """A type an operator setting an environment variable can act on."""
    text = str(annotation)
    text = text.replace("typing.", "").replace("<class '", "").replace("'>", "")
    # `OptionalInt` and friends are Annotated aliases; the validator in them is
    # an implementation detail of "an empty string means unset".
    if "Annotated[" in text:
        text = text.split("Annotated[", 1)[1].split(",", 1)[0]
    if text.startswith("Literal["):
        options = text[len("Literal[") : -1].split(", ")
        return " \\| ".join(f"`{option.strip(chr(39))}`" for option in options)
    text = text.replace(" | None", "").replace("Optional[", "").rstrip("]")
    return f"`{text}`"


def _constraint(metadata: list[Any]) -> str:
    parts: list[str] = []
    for item in metadata:
        for symbol, attribute in (("≥", "ge"), (">", "gt"), ("≤", "le"), ("<", "lt")):
            bound = getattr(item, attribute, None)
            if bound is not None:
                parts.append(f"{symbol} {bound}")
    return ", ".join(parts)


def collect() -> list[Entry]:
    from crypto_processing_api.config import Settings

    descriptions, sections = _source_metadata()
    entries: list[Entry] = []
    for name, info in Settings.model_fields.items():
        entries.append(
            Entry(
                name=name.upper(),
                section=sections.get(name, ""),
                annotation=_render_type(info.annotation),
                description=descriptions.get(name, ""),
                default=_render_default(info.default) if not info.is_required() else "—",
                required=info.is_required(),
                constraint=_constraint(list(info.metadata)),
                secret=any(part in name for part in SECRET_SUBSTRINGS),
            )
        )
    return entries


def render(entries: list[Entry]) -> str:
    out = [HEADER]
    section = None
    for entry in entries:
        if entry.section != section:
            section = entry.section
            out.append(f"\n## {section or 'Other'}\n")
            out.append("| Variable | Type | Default | Notes |")
            out.append("|---|---|---|---|")
        notes: list[str] = []
        if entry.required:
            notes.append("**required**")
        if entry.secret:
            notes.append("**secret**")
        if entry.constraint:
            notes.append(entry.constraint)
        if entry.description:
            notes.append(entry.description)
        out.append(
            f"| `{entry.name}` | {entry.annotation} | {entry.default} | "
            f"{' — '.join(notes) if notes else ''} |"
        )

    out.append(RULES_HEADING)
    out.extend(f"- {rule}" for rule in STARTUP_RULES)
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if the committed page is not what the code produces",
    )
    args = parser.parse_args(argv)

    rendered = render(collect())
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else None
    relative = OUTPUT_PATH.relative_to(REPO_ROOT).as_posix()

    if current == rendered:
        if args.check:
            print("the committed configuration reference matches the code")
        return 0

    if args.check:
        print(
            f"::error file={relative}::out of date; run "
            "`python scripts/export_config_reference.py` and commit the result",
            file=sys.stderr,
        )
        return 1

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
