"""Emit the webhook event types for both SDKs from the committed JSON Schema.

`docs/reference/webhook-events.json` is the contract for the eight outbound
events. No OpenAPI generator reads it, because the events are not responses —
so this writes the types both SDKs' `parse_event` returns:

    sdks/python/crypto_processing_client/event_types.py
    sdks/typescript/src/event-types.ts

Why a script here rather than a third-party generator per language: the schema
uses five shapes and only five, the output is a few hundred lines of
declarations, and two more pinned toolchains would be two more things to keep
alive for a one-maintainer project. The safety comes from refusing what it does
not understand — an unrecognised schema shape stops generation with the
property named, instead of quietly emitting `Any`.

Both files are drift-gated. Run this after `scripts/export_openapi.py`.

    python scripts/generate_event_types.py           # write
    python scripts/generate_event_types.py --check   # exit 1 if stale
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "docs" / "reference" / "webhook-events.json"
PYTHON_PATH = REPO_ROOT / "sdks" / "python" / "crypto_processing_client" / "event_types.py"
TYPESCRIPT_PATH = REPO_ROOT / "sdks" / "typescript" / "src" / "event-types.ts"

BANNER = "Generated by scripts/generate_event_types.py from docs/reference/webhook-events.json."
DO_NOT_EDIT = "Do not edit: CI regenerates this file and fails on any difference."


class UnsupportedSchema(Exception):
    """A shape the emitter has never seen. Better a stopped build than a wrong type."""


def _load() -> dict[str, Any]:
    document: dict[str, Any] = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    return document


def _ref_name(schema: dict[str, Any]) -> str | None:
    ref = schema.get("$ref")
    if ref is None:
        return None
    if not ref.startswith("#/$defs/"):
        raise UnsupportedSchema(f"only local $defs refs are understood, got {ref!r}")
    return ref.removeprefix("#/$defs/")


def _nullable_inner(schema: dict[str, Any]) -> dict[str, Any] | None:
    """`anyOf: [X, null]` is how pydantic writes an optional field."""
    options = schema.get("anyOf")
    if not options:
        return None
    concrete = [option for option in options if option.get("type") != "null"]
    if len(concrete) != 1 or len(concrete) == len(options):
        raise UnsupportedSchema(f"anyOf must be exactly one type plus null, got {options!r}")
    return concrete[0]


def _render(schema: dict[str, Any], *, string: str, array: str, optional: str, const: str) -> str:
    """One walk over the schema, two languages, so they cannot drift apart."""
    name = _ref_name(schema)
    if name is not None:
        return name
    inner = _nullable_inner(schema)
    if inner is not None:
        return optional.format(
            _render(inner, string=string, array=array, optional=optional, const=const)
        )
    if "const" in schema:
        literal = schema["const"]
        if not isinstance(literal, str):
            raise UnsupportedSchema(f"only string consts are understood, got {literal!r}")
        return const.format(literal)
    if schema.get("type") == "string":
        return string
    if schema.get("type") == "array":
        items = schema.get("items")
        if not isinstance(items, dict):
            raise UnsupportedSchema("an array without a single item schema")
        return array.format(
            _render(items, string=string, array=array, optional=optional, const=const)
        )
    raise UnsupportedSchema(f"no mapping for {schema!r}")


def _python_type(schema: dict[str, Any]) -> str:
    return _render(
        schema, string="str", array="list[{}]", optional="{} | None", const='Literal["{}"]'
    )


def _typescript_type(schema: dict[str, Any]) -> str:
    return _render(schema, string="string", array="{}[]", optional="{} | null", const="'{}'")


def _fields(definition: dict[str, Any]) -> list[tuple[str, dict[str, Any], bool]]:
    """Required fields in the model's own order, then anything else, sorted."""
    properties: dict[str, Any] = definition["properties"]
    required: list[str] = list(definition.get("required", []))
    ordered = required + sorted(set(properties) - set(required))
    return [(name, properties[name], name in required) for name in ordered]


def _doc(definition: dict[str, Any]) -> list[str]:
    text = definition.get("description", "").strip()
    return text.splitlines() if text else []


def _describe(schema: dict[str, Any], *, prefix: str, width: int = 96) -> list[str]:
    """A property's description as comment lines, wrapped so nothing runs long."""
    description = schema.get("description")
    if not description:
        return []
    return textwrap.wrap(
        " ".join(description.split()), width=width, initial_indent=prefix, subsequent_indent=prefix
    )


def _envelopes(document: dict[str, Any]) -> dict[str, str]:
    """Event type -> envelope definition name, from the discriminator mapping."""
    mapping: dict[str, str] = document["discriminator"]["mapping"]
    return {event_type: ref.removeprefix("#/$defs/") for event_type, ref in sorted(mapping.items())}


def _data_models(document: dict[str, Any], envelopes: dict[str, str]) -> list[str]:
    """The payload models, which must be declared before the envelopes use them."""
    return sorted(set(document["$defs"]) - set(envelopes.values()))


def build_python(document: dict[str, Any]) -> str:
    defs = document["$defs"]
    envelopes = _envelopes(document)
    lines: list[str] = [
        '"""Typed shapes of the eight outbound webhook events.',
        "",
        BANNER,
        DO_NOT_EDIT,
        "",
        "These are `TypedDict`s rather than validating models on purpose. The",
        "documented contract is to parse defensively — ignore fields you do not",
        "know, skip an event type you do not know — and a validating model does",
        "the opposite of that on the day the server adds a field.",
        "",
        "`type` is a `Literal`, so a type checker narrows the union for you:",
        "",
        '    if event["type"] == "deposit.settled":',
        '        credit(event["data"]["amount_credited"])',
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Literal, NotRequired, TypedDict",
        "",
        "",
    ]

    for name in _data_models(document, envelopes):
        lines += _python_class(name, defs[name])
    for name in envelopes.values():
        lines += _python_class(name, defs[name])

    union = "\n    | ".join(envelopes.values())
    lines += [
        "#: Every event the service sends, discriminated on `type`.",
        f"PlatformEvent = (\n    {union}\n)",
        "",
        "#: The `type` values, as a type. A platform can switch exhaustively over it.",
        "EventType = Literal[",
    ]
    lines += [f'    "{event_type}",' for event_type in envelopes]
    lines += [
        "]",
        "",
        "#: The same closed set at runtime, in the order the schema lists it.",
        "EVENT_TYPES: tuple[EventType, ...] = (",
    ]
    lines += [f'    "{event_type}",' for event_type in envelopes]
    lines += [")", ""]
    return "\n".join(lines)


def _python_class(name: str, definition: dict[str, Any]) -> list[str]:
    lines = [f"class {name}(TypedDict):"]
    doc = _doc(definition)
    if len(doc) == 1:
        lines += [f'    """{doc[0]}"""', ""]
    elif doc:
        lines += [f'    """{doc[0]}']
        lines += [f"    {line}".rstrip() for line in doc[1:]]
        lines += ['    """', ""]
    for field, schema, required in _fields(definition):
        rendered = _python_type(schema)
        if not required:
            rendered = f"NotRequired[{rendered}]"
        lines += _describe(schema, prefix="    # ")
        lines.append(f"    {field}: {rendered}")
    lines += ["", ""]
    return lines


def build_typescript(document: dict[str, Any]) -> str:
    defs = document["$defs"]
    envelopes = _envelopes(document)
    lines: list[str] = [
        "/**",
        " * Typed shapes of the eight outbound webhook events.",
        " *",
        f" * {BANNER}",
        f" * {DO_NOT_EDIT}",
        " *",
        " * `type` is a literal, so the union narrows on a switch:",
        " *",
        " *     if (event.type === 'deposit.settled') {",
        " *       credit(event.data.amount_credited);",
        " *     }",
        " */",
        "",
    ]

    for name in _data_models(document, envelopes):
        lines += _typescript_interface(name, defs[name])
    for name in envelopes.values():
        lines += _typescript_interface(name, defs[name])

    union = "\n  | ".join(envelopes.values())
    lines += [
        "/** Every event the service sends, discriminated on `type`. */",
        f"export type PlatformEvent =\n  | {union};",
        "",
        "/** The `type` values, as a type. */",
        "export type EventType = PlatformEvent['type'];",
        "",
        "/** The same closed set at runtime, in the order the schema lists it. */",
        "export const EVENT_TYPES = [",
    ]
    lines += [f"  '{event_type}'," for event_type in envelopes]
    lines += ["] as const satisfies readonly EventType[];", ""]
    return "\n".join(lines)


def _typescript_interface(name: str, definition: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    doc = _doc(definition)
    if doc:
        lines.append("/**")
        lines += [f" * {line}".rstrip() for line in doc]
        lines.append(" */")
    lines.append(f"export interface {name} {{")
    for field, schema, required in _fields(definition):
        comment = _describe(schema, prefix="   * ", width=94)
        if len(comment) == 1:
            lines.append(f"  /** {comment[0].strip()} */")
        elif comment:
            lines += ["  /**", *comment, "   */"]
        lines.append(f"  {field}{'' if required else '?'}: {_typescript_type(schema)};")
    lines += ["}", ""]
    return lines


def build() -> dict[Path, str]:
    document = _load()
    return {
        PYTHON_PATH: build_python(document),
        TYPESCRIPT_PATH: build_typescript(document),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if a committed file is not what the schema produces",
    )
    args = parser.parse_args(argv)

    stale: list[Path] = []
    for path, rendered in build().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == rendered:
            continue
        if args.check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO_ROOT).as_posix()}")

    if stale:
        for path in stale:
            print(
                f"::error file={path.relative_to(REPO_ROOT).as_posix()}::"
                "out of date; run `python scripts/generate_event_types.py` and commit it",
                file=sys.stderr,
            )
        return 1
    if args.check:
        print("the committed event types match the schema")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
