/**
 * This client's verifier must agree with the server's, case for case.
 *
 * `sdks/signature-vectors.json` is generated by the server's own signer and is
 * asserted by the server suite, the Python suite and this one. It is the only
 * thing that makes "the SDK verifies webhooks correctly" a checkable claim
 * rather than a hope.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  EVENT_TYPES,
  REPLAY_WINDOW_SECONDS,
  SIGNATURE_HEADER,
  parseEventUnverified,
  verifyWebhook,
} from '../src/index.js';

interface Vectors {
  scheme: { header: string; replay_window_seconds: number };
  bodies: Record<string, { base64: string; utf8?: string; description: string }>;
  sign: Array<{ name: string; body: string; secret: string; timestamp: number; signature: string }>;
  verify: Array<{
    name: string;
    body: string;
    secret: string;
    header: string;
    now: number;
    valid: boolean;
    why: string;
  }>;
}

const VECTORS_PATH = fileURLToPath(new URL('../../signature-vectors.json', import.meta.url));
const vectors = JSON.parse(readFileSync(VECTORS_PATH, 'utf-8')) as Vectors;

function bodyOf(name: string): Uint8Array {
  const entry = vectors.bodies[name];
  if (!entry) throw new Error(`no body named ${name} in the vectors file`);
  return Uint8Array.from(Buffer.from(entry.base64, 'base64'));
}

it('the scheme constants match the server', () => {
  expect(vectors.scheme.header).toBe(SIGNATURE_HEADER);
  expect(vectors.scheme.replay_window_seconds).toBe(REPLAY_WINDOW_SECONDS);
});

describe('every signed vector verifies', () => {
  for (const testCase of vectors.sign) {
    it(testCase.name, async () => {
      await expect(
        verifyWebhook(bodyOf(testCase.body), testCase.signature, testCase.secret, {
          now: testCase.timestamp,
        }),
      ).resolves.toBe(true);
    });
  }
});

describe('every verify vector gets the same answer', () => {
  for (const testCase of vectors.verify) {
    it(`${testCase.name} — ${testCase.why}`, async () => {
      await expect(
        verifyWebhook(bodyOf(testCase.body), testCase.header, testCase.secret, {
          now: testCase.now,
        }),
      ).resolves.toBe(testCase.valid);
    });
  }
});

it('the matrix contains refusals', () => {
  // Guards the guard: passing cases alone would be satisfied by `return true`.
  const answers = new Set(vectors.verify.map((testCase) => testCase.valid));
  expect([...answers].sort()).toEqual([false, true]);
});

describe('every real event body parses', () => {
  for (const eventType of EVENT_TYPES) {
    it(eventType, () => {
      // The vector bodies are the delivery worker's own bytes, not a hand-typed
      // sample, so this also pins the shape the server really sends.
      const event = parseEventUnverified(bodyOf(`event.${eventType}`));
      expect(event.type).toBe(eventType);
      expect(event.id.startsWith('evt_')).toBe(true);
      expect(event.data).toBeTruthy();
    });
  }
});
