"""The BOLT11 decoder, against invoices a real LND actually signed.

Every sample here was generated by LND 0.19.3 on the regtest stack during the
R4 Lightning spike and committed alongside the Greenfield payloads it produced.
That matters more than usual: the decoder's output is cross-checkable against
BTCPay's own view of the same invoice, so these tests do not merely assert that
the decoder agrees with itself.

The strongest of those cross-checks is
`test_the_decoded_payment_hash_matches_btcpays_payment_proof`. It derives 32
bytes from 283 characters of bech32 and asserts them equal to a field BTCPay
independently reported for the same payment. Nothing else in this file could
pass by accident if that one does.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from crypto_processing_api.core.addresses import (
    BECH32_CHARSET,
    BECH32_CONST,
    DEFAULT_INVOICE_EXPIRY_SECONDS,
    AddressError,
    _bech32_hrp_expand,
    _bech32_polymod,
    decode_bolt11,
)

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "greenfield"


def load(name: str) -> Any:
    return json.loads((FIXTURES / f"{name}.json").read_text(encoding="utf-8"))


def reprefix(invoice: str, hrp: str) -> str:
    """Re-checksum a real invoice under a different human-readable part.

    The signature no longer covers the amount, which is fine — nothing here
    checks signatures. What it buys is a *checksum-valid* invoice for a chain
    this service does not serve, which is the only way to reach the prefix
    check: the checksum is verified first, on purpose, so a fabricated string
    never gets as far as being parsed.
    """
    data = [BECH32_CHARSET.index(c) for c in invoice[invoice.rfind("1") + 1 : -6]]
    checksum = _bech32_polymod(_bech32_hrp_expand(hrp) + data + [0] * 6) ^ BECH32_CONST
    tail = [(checksum >> 5 * (5 - index)) & 31 for index in range(6)]
    return hrp + "1" + "".join(BECH32_CHARSET[value] for value in data + tail)


@pytest.fixture(scope="module")
def samples() -> dict[str, str]:
    return dict(load("ln_bolt11_samples"))


def test_an_amountless_deposit_invoice_decodes(samples: dict[str, str]) -> None:
    """The deposit shape: BTCPay hands out a zero-amount BOLT11 for a top-up."""
    invoice = decode_bolt11(samples["paid_deposit"], network="regtest")

    assert invoice.amount_msat is None
    assert invoice.amount_sat is None
    assert invoice.network == "regtest"
    assert len(invoice.payment_hash) == 64
    assert int(invoice.payment_hash, 16) > 0


@pytest.mark.parametrize(
    ("sample", "expected_sat"),
    [
        # 1200u is 1200 micro-bitcoin; BTCPay reported this payout as 0.0012.
        ("payout_completed", 120_000),
        # 90m is 90 milli-bitcoin; BTCPay reported that payout as 0.09.
        ("payout_never_routed", 9_000_000),
        ("payout_expired_before_creation", 50_000),
    ],
)
def test_the_amount_multipliers_are_read_correctly(
    samples: dict[str, str], sample: str, expected_sat: int
) -> None:
    """Reading `m` as `u` would send a thousand times the right amount."""
    assert decode_bolt11(samples[sample], network="regtest").amount_sat == expected_sat


def test_the_decoded_payment_hash_matches_btcpays_payment_proof(
    samples: dict[str, str],
) -> None:
    """The cross-check that makes the rest of this file worth trusting.

    BTCPay reports the payment hash on a completed Lightning payout. The
    decoder derives it from the invoice string alone. They must be the same 32
    bytes, because a stuck payout has no payment proof at all and the hash then
    has to come from the invoice — it is the only handle on "did this payment
    ever leave".
    """
    decoded = decode_bolt11(samples["payout_completed"], network="regtest")
    proof = load("ln_payout_completed")["paymentProof"]

    assert decoded.payment_hash == proof["PaymentHash"]
    assert decoded.payment_hash == proof["Id"]


def test_the_decoded_payment_hash_matches_the_invoices_own_payment_id(
    samples: dict[str, str],
) -> None:
    """On Lightning the payment id *is* the payment hash, unlike on chain."""
    decoded = decode_bolt11(samples["paid_deposit"], network="regtest")
    method = next(
        m for m in load("ln_invoice_payment_methods_settled") if m["paymentMethodId"] == "BTC-LN"
    )

    assert decoded.payment_hash == method["additionalData"]["paymentHash"]
    assert decoded.payment_hash == method["payments"][0]["id"]


def test_an_explicit_expiry_is_read_from_the_invoice(samples: dict[str, str]) -> None:
    """This one was generated with `--expiry 60` to be expired on purpose."""
    invoice = decode_bolt11(samples["payout_expired_before_creation"], network="regtest")

    assert invoice.expiry_seconds == 60
    assert invoice.expires_at == datetime.fromtimestamp(invoice.timestamp + 60, tz=UTC)
    assert invoice.expires_at < datetime.now(UTC), "the sample was supposed to be long expired"


def test_a_missing_expiry_field_means_one_hour(samples: dict[str, str]) -> None:
    """BOLT 11's default. Assuming "no expiry" instead would let a withdrawal
    be submitted against an invoice no node will settle."""
    invoice = decode_bolt11(samples["payout_never_routed"], network="regtest")
    assert invoice.expiry_seconds == DEFAULT_INVOICE_EXPIRY_SECONDS


def test_the_timestamp_is_a_plausible_moment(samples: dict[str, str]) -> None:
    """A misread timestamp shifts every expiry decision with it."""
    invoice = decode_bolt11(samples["payout_completed"], network="regtest")
    signed_at = datetime.fromtimestamp(invoice.timestamp, tz=UTC)

    assert datetime(2020, 1, 1, tzinfo=UTC) < signed_at < datetime(2100, 1, 1, tzinfo=UTC)


def test_a_regtest_invoice_is_refused_on_mainnet(samples: dict[str, str]) -> None:
    """The failure that costs real money, in the direction that costs it."""
    with pytest.raises(AddressError, match="not mainnet"):
        decode_bolt11(samples["payout_completed"], network="mainnet")


def test_a_single_mistyped_character_is_refused(samples: dict[str, str]) -> None:
    """The checksum is the whole reason to decode rather than pattern-match."""
    original = samples["payout_completed"]
    # Swap one character in the data part for a different one in the charset.
    broken = original[:-5] + ("q" if original[-5] != "q" else "p") + original[-4:]

    with pytest.raises(AddressError, match="checksum"):
        decode_bolt11(broken, network="regtest")


def test_the_lightning_uri_prefix_is_accepted(samples: dict[str, str]) -> None:
    """BTCPay's own `paymentLink` carries it, and so does every wallet's QR."""
    bare = decode_bolt11(samples["payout_completed"], network="regtest")
    prefixed = decode_bolt11(f"lightning:{samples['payout_completed']}", network="regtest")

    assert prefixed == bare


@pytest.mark.parametrize(
    ("candidate", "expected"),
    [
        ("", "empty"),
        ("  ", "empty"),
        ("bcrt1qkfycfk4zd2c907ychq502p5seze67nsny0kqxq", "starts with 'ln'"),
        ("lnbcrt", "malformed"),
        # A fabricated string never reaches the parser: the checksum is checked
        # first, so this is the error it must produce.
        ("lnltc1p485s33qqqqqq", "checksum"),
    ],
)
def test_things_that_are_not_invoices_are_refused(candidate: str, expected: str) -> None:
    with pytest.raises(AddressError, match=expected):
        decode_bolt11(candidate, network="regtest")


def test_another_chains_lightning_invoice_is_refused(samples: dict[str, str]) -> None:
    """Litecoin has Lightning too, and `lnltc` is a plausible paste."""
    with pytest.raises(AddressError, match="not a bitcoin BOLT11 prefix"):
        decode_bolt11(reprefix(samples["payout_completed"], "lnltc"), network="regtest")


def test_the_amount_survives_a_reprefix(samples: dict[str, str]) -> None:
    """Proves `reprefix` builds a genuinely valid invoice rather than one the
    decoder happens to reject for a second reason."""
    rebuilt = decode_bolt11(reprefix(samples["payout_completed"], "lnbcrt1200u"), network="regtest")
    assert rebuilt.amount_sat == 120_000


def test_a_bitcoin_address_is_not_a_lightning_destination() -> None:
    """The mix-up a platform integration actually makes."""
    with pytest.raises(AddressError):
        decode_bolt11("bcrt1qkfycfk4zd2c907ychq502p5seze67nsny0kqxq", network="regtest")


def test_whitespace_is_refused(samples: dict[str, str]) -> None:
    with pytest.raises(AddressError, match="whitespace"):
        decode_bolt11(f" {samples['payout_completed']}", network="regtest")


def test_an_unknown_network_is_refused(samples: dict[str, str]) -> None:
    with pytest.raises(AddressError, match="unknown bitcoin network"):
        decode_bolt11(samples["payout_completed"], network="nile")


def test_every_committed_sample_decodes_on_regtest(samples: dict[str, str]) -> None:
    """A corpus with a sample nobody parses proves nothing about that sample."""
    assert len(samples) == 4
    for name, invoice in samples.items():
        decoded = decode_bolt11(invoice, network="regtest")
        assert len(decoded.payment_hash) == 64, name
