"""Address validation vectors.

The BIP 173 / BIP 350 test vectors are here because a validator that accepts a
wrong-network or bad-checksum address turns a 422 into locked user funds and a
support ticket.
"""

from __future__ import annotations

import pytest

from crypto_processing_api.core.addresses import (
    AddressError,
    AddressKind,
    validate_bitcoin_address,
)

# Real mainnet addresses from the BIP test vectors and the genesis block.
MAINNET_P2PKH = "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa"
MAINNET_P2SH = "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy"
MAINNET_P2WPKH = "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4"
MAINNET_P2WSH = "bc1qrp33g0q5c5txsp9arysrx4k6zdkfs4nce4xj0gdcccefvpysxf3qccfmv3"
MAINNET_P2TR = "bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vqzk5jj0"

TESTNET_P2WPKH = "tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx"
TESTNET_P2PKH = "mipcBbFg9gMiCh81Kj8tqqdgoZub1ZJRfn"

# Generated by the regtest node during the M2 drills.
REGTEST_P2WPKH = "bcrt1qdcaqy5dph55w0nyfg2zdu7nkrmzwpkwsej29yq"


@pytest.mark.parametrize(
    ("address", "kind"),
    [
        (MAINNET_P2PKH, AddressKind.P2PKH),
        (MAINNET_P2SH, AddressKind.P2SH),
        (MAINNET_P2WPKH, AddressKind.SEGWIT_V0),
        (MAINNET_P2WSH, AddressKind.SEGWIT_V0),
        (MAINNET_P2TR, AddressKind.SEGWIT_V1),
    ],
)
def test_valid_mainnet_addresses(address: str, kind: AddressKind) -> None:
    assert validate_bitcoin_address(address, network="mainnet") == kind


def test_valid_testnet_addresses() -> None:
    assert validate_bitcoin_address(TESTNET_P2WPKH, network="testnet") == AddressKind.SEGWIT_V0
    assert validate_bitcoin_address(TESTNET_P2PKH, network="testnet") == AddressKind.P2PKH


def test_valid_regtest_address() -> None:
    assert validate_bitcoin_address(REGTEST_P2WPKH, network="regtest") == AddressKind.SEGWIT_V0


def test_uppercase_bech32_is_valid() -> None:
    assert (
        validate_bitcoin_address(MAINNET_P2WPKH.upper(), network="mainnet") == AddressKind.SEGWIT_V0
    )


# -- wrong network ---------------------------------------------------------


@pytest.mark.parametrize(
    ("address", "network"),
    [
        (MAINNET_P2WPKH, "testnet"),
        (MAINNET_P2WPKH, "regtest"),
        (TESTNET_P2WPKH, "mainnet"),
        (REGTEST_P2WPKH, "mainnet"),
        (REGTEST_P2WPKH, "testnet"),
        (MAINNET_P2PKH, "testnet"),
        (TESTNET_P2PKH, "mainnet"),
    ],
)
def test_wrong_network_is_rejected(address: str, network: str) -> None:
    """The mistake that sends real coins somewhere unspendable."""
    with pytest.raises(AddressError):
        validate_bitcoin_address(address, network=network)


def test_regtest_and_testnet_share_base58_versions() -> None:
    """An honest limitation, stated as a test so nobody assumes otherwise."""
    assert validate_bitcoin_address(TESTNET_P2PKH, network="regtest") == AddressKind.P2PKH


# -- corruption ------------------------------------------------------------


def test_single_character_typo_in_bech32_is_caught() -> None:
    broken = MAINNET_P2WPKH[:-1] + ("4" if MAINNET_P2WPKH[-1] != "4" else "5")
    with pytest.raises(AddressError, match="checksum"):
        validate_bitcoin_address(broken, network="mainnet")


def test_single_character_typo_in_base58_is_caught() -> None:
    broken = MAINNET_P2PKH[:-1] + ("A" if MAINNET_P2PKH[-1] != "A" else "B")
    with pytest.raises(AddressError, match="checksum"):
        validate_bitcoin_address(broken, network="mainnet")


def test_taproot_with_the_segwit_v0_checksum_is_rejected() -> None:
    """BIP 350: version 1+ uses bech32m. Accepting bech32 here pays nobody."""
    # bc1p... encoded with the bech32 constant instead of bech32m.
    with pytest.raises(AddressError, match="checksum"):
        validate_bitcoin_address(
            "bc1p0xlxvlhemja6c4dqv22uapctqupfhlxm9h8z3k2e72q4k9hcz7vq5zuyut",
            network="mainnet",
        )


def test_segwit_v0_with_the_bech32m_checksum_is_rejected() -> None:
    with pytest.raises(AddressError, match="checksum"):
        validate_bitcoin_address("bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kemeawh", network="mainnet")


@pytest.mark.parametrize(
    "address",
    [
        "",
        "   ",
        "not-an-address",
        "bc1",
        "bc1q",
        "0x0000000000000000000000000000000000000000",  # an Ethereum address
        "TQn9Y2khEsLJW1ChVWFMSMeRDow5KcbLSE",  # a TRON address
        "bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4 ",  # trailing space
        " bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",
        "1A1zP1eP5QGefi2DMPTfTL5SLmv7Div0Na",  # base58 with a '0'
        "bc1Qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4",  # mixed case
    ],
)
def test_garbage_is_rejected(address: str) -> None:
    with pytest.raises(AddressError):
        validate_bitcoin_address(address, network="mainnet")


def test_bech32_over_ninety_characters_is_rejected() -> None:
    with pytest.raises(AddressError, match="malformed"):
        validate_bitcoin_address("bc1" + "q" * 95, network="mainnet")


def test_unknown_network_is_a_programming_error() -> None:
    with pytest.raises(AddressError, match="unknown bitcoin network"):
        validate_bitcoin_address(MAINNET_P2WPKH, network="mars")
