"""Python client for crypto-processing-api.

    from crypto_processing_client import CryptoProcessingClient, parse_event

    client = CryptoProcessingClient("https://pay.example.com", api_key="cpk_live_...")
    deposit = client.create_deposit(external_user_id="user-42", asset="BTC")

The version tracks the server it supports: `client 0.N.x` works against
`server 0.N.y`. See `docs/reference/versioning.md` in the repository.

Two layers live here. `crypto_processing_client._generated` is produced from
the server's committed OpenAPI document and is regenerated by CI, which fails
on any difference — so it cannot describe a server that does not exist. This
module is the handwritten part: idempotency keys, retries, typed errors and
webhook verification, none of which codegen can write.
"""

from __future__ import annotations

from ._generated.models import (
    AddressHistoryResponse,
    AdminDepositQueueResponse,
    AdminResolveDepositResponse,
    AdminWithdrawalListResponse,
    AdminWithdrawalResponse,
    AssetResponse,
    AssetsResponse,
    BalanceResponse,
    BalancesResponse,
    ComponentResponse,
    DepositListResponse,
    DepositPaymentResponse,
    DepositResponse,
    HealthResponse,
    OutboundEventResponse,
    OutboundEventsResponse,
    ReadyResponse,
    ReconciliationResponse,
    RedeliverEventResponse,
    TransactionResponse,
    TransactionsResponse,
    WalletAlertResponse,
    WalletAlertsResponse,
    WithdrawalCreatedResponse,
    WithdrawalListResponse,
    WithdrawalResponse,
)
from .client import CryptoProcessingClient, RetryPolicy
from .errors import (
    APIError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    CryptoProcessingError,
    NotFoundError,
    PermissionDeniedError,
    ServerError,
    ServiceUnavailableError,
    TransportError,
    UnknownEventTypeError,
    UpstreamRefusedError,
    ValidationError,
    WebhookVerificationError,
)
from .event_types import (
    EVENT_TYPES,
    DepositDetectedData,
    DepositDetectedEvent,
    DepositEventData,
    DepositExpiredEvent,
    DepositReviewRequiredEvent,
    DepositSettledEvent,
    EventType,
    PlatformEvent,
    WithdrawalBroadcastEvent,
    WithdrawalCompletedEvent,
    WithdrawalDecisionData,
    WithdrawalEventData,
    WithdrawalFailedEvent,
    WithdrawalPendingApprovalEvent,
)
from .webhooks import (
    REPLAY_WINDOW_SECONDS,
    SIGNATURE_HEADER,
    parse_event,
    parse_event_unverified,
    verify_webhook,
)

__version__ = "0.2.0"

__all__ = [
    "EVENT_TYPES",
    "REPLAY_WINDOW_SECONDS",
    "SIGNATURE_HEADER",
    "APIError",
    "AddressHistoryResponse",
    "AdminDepositQueueResponse",
    "AdminResolveDepositResponse",
    "AdminWithdrawalListResponse",
    "AdminWithdrawalResponse",
    "AssetResponse",
    "AssetsResponse",
    "AuthenticationError",
    "BadRequestError",
    "BalanceResponse",
    "BalancesResponse",
    "ComponentResponse",
    "ConflictError",
    "CryptoProcessingClient",
    "CryptoProcessingError",
    "DepositDetectedData",
    "DepositDetectedEvent",
    "DepositEventData",
    "DepositExpiredEvent",
    "DepositListResponse",
    "DepositPaymentResponse",
    "DepositResponse",
    "DepositReviewRequiredEvent",
    "DepositSettledEvent",
    "EventType",
    "HealthResponse",
    "NotFoundError",
    "OutboundEventResponse",
    "OutboundEventsResponse",
    "PermissionDeniedError",
    "PlatformEvent",
    "ReadyResponse",
    "ReconciliationResponse",
    "RedeliverEventResponse",
    "RetryPolicy",
    "ServerError",
    "ServiceUnavailableError",
    "TransactionResponse",
    "TransactionsResponse",
    "TransportError",
    "UnknownEventTypeError",
    "UpstreamRefusedError",
    "ValidationError",
    "WalletAlertResponse",
    "WalletAlertsResponse",
    "WebhookVerificationError",
    "WithdrawalBroadcastEvent",
    "WithdrawalCompletedEvent",
    "WithdrawalCreatedResponse",
    "WithdrawalDecisionData",
    "WithdrawalEventData",
    "WithdrawalFailedEvent",
    "WithdrawalListResponse",
    "WithdrawalPendingApprovalEvent",
    "WithdrawalResponse",
    "__version__",
    "parse_event",
    "parse_event_unverified",
    "verify_webhook",
]
