"""Typed shapes of the eight outbound webhook events.

Generated by scripts/generate_event_types.py from docs/reference/webhook-events.json.
Do not edit: CI regenerates this file and fails on any difference.

These are `TypedDict`s rather than validating models on purpose. The
documented contract is to parse defensively — ignore fields you do not
know, skip an event type you do not know — and a validating model does
the opposite of that on the day the server adds a field.

`type` is a `Literal`, so a type checker narrows the union for you:

    if event["type"] == "deposit.settled":
        credit(event["data"]["amount_credited"])
"""

from __future__ import annotations

from typing import Literal, NotRequired, TypedDict


class DepositDetectedData(TypedDict):
    """A payment is visible. It is **not** credited yet — `amount_credited` may still be zero."""

    deposit_id: str
    external_user_id: str
    asset: str
    status: str
    # Decimal string, the running total credited to the user for this deposit.
    amount_credited: str
    # BTCPay payment ids recorded by this update.
    payments: list[str]


class DepositEventData(TypedDict):
    deposit_id: str
    external_user_id: str
    asset: str
    status: str
    # Decimal string, the running total credited to the user for this deposit.
    amount_credited: str


class WithdrawalDecisionData(TypedDict):
    """A withdrawal that stopped, or stopped to wait. The reason is always present.

    Every path that queues a withdrawal names the gate that fired, and every
    path that fails one names why, so this field is required rather than
    optional — a `withdrawal.failed` with no reason would be the one event an
    operator cannot act on.
    """

    withdrawal_id: str
    external_user_id: str
    asset: str
    status: str
    amount_gross: str
    # `null` until submission fixes the fee.
    amount_net: str | None
    # `null` until submission fixes the fee.
    fee: str | None
    destination_address: str
    txid: str | None
    # For `pending_approval`, which gate fired. For `failed`, why it will not proceed —
    # including a machine-generated definitive-failure proof where the backend can produce one.
    reason: str


class WithdrawalEventData(TypedDict):
    withdrawal_id: str
    external_user_id: str
    asset: str
    status: str
    amount_gross: str
    # `null` until submission fixes the fee.
    amount_net: str | None
    # `null` until submission fixes the fee.
    fee: str | None
    destination_address: str
    txid: str | None


class DepositDetectedEvent(TypedDict):
    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["deposit.detected"]
    data: DepositDetectedData


class DepositExpiredEvent(TypedDict):
    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["deposit.expired"]
    data: DepositEventData


class DepositReviewRequiredEvent(TypedDict):
    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["deposit.review_required"]
    data: DepositEventData


class DepositSettledEvent(TypedDict):
    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["deposit.settled"]
    data: DepositEventData


class WithdrawalBroadcastEvent(TypedDict):
    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["withdrawal.broadcast"]
    data: WithdrawalEventData


class WithdrawalCompletedEvent(TypedDict):
    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["withdrawal.completed"]
    data: WithdrawalEventData


class WithdrawalFailedEvent(TypedDict):
    """**The money is not back yet.** A failed withdrawal still holds the balance."""

    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["withdrawal.failed"]
    data: WithdrawalDecisionData


class WithdrawalPendingApprovalEvent(TypedDict):
    # Stable and `evt_`-prefixed. Dedup on it: the same id may arrive twice.
    id: str
    created_at: str
    type: Literal["withdrawal.pending_approval"]
    data: WithdrawalDecisionData


#: Every event the service sends, discriminated on `type`.
PlatformEvent = (
    DepositDetectedEvent
    | DepositExpiredEvent
    | DepositReviewRequiredEvent
    | DepositSettledEvent
    | WithdrawalBroadcastEvent
    | WithdrawalCompletedEvent
    | WithdrawalFailedEvent
    | WithdrawalPendingApprovalEvent
)

#: The `type` values, as a type. A platform can switch exhaustively over it.
EventType = Literal[
    "deposit.detected",
    "deposit.expired",
    "deposit.review_required",
    "deposit.settled",
    "withdrawal.broadcast",
    "withdrawal.completed",
    "withdrawal.failed",
    "withdrawal.pending_approval",
]

#: The same closed set at runtime, in the order the schema lists it.
EVENT_TYPES: tuple[EventType, ...] = (
    "deposit.detected",
    "deposit.expired",
    "deposit.review_required",
    "deposit.settled",
    "withdrawal.broadcast",
    "withdrawal.completed",
    "withdrawal.failed",
    "withdrawal.pending_approval",
)
